{% set name = "compas_fab" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73825df139a606d3b3084e99daca20838706ea352483389f3a64b84bd2fffd3f

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - tomli                   # This is because build is breaking https://github.com/twisted/incremental/issues/106
    - compas >=2.0.4,<3
    - compas_robots >=0.3,<1
    - roslibpy >=1.1.0
    - pyserial
    - pybullet
    - python

test:
  imports:
    - compas_fab
    - compas_fab.backends
    - compas_fab.robots
    - compas_fab.rhino
    - compas_fab.blender
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/compas-dev/compas_fab
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Robotic fabrication package for the COMPAS Framework
  description: |
    Robotic fabrication package for the COMPAS Framework facilitating the
    planning and execution of robotic fabrication processes. It provides
    interfaces to existing software libraries and tools available in the
    field of robotics (e.g. OMPL, ROS, PyBullet) and makes them accessible
    from within the parametric design environment. The package builds upon
    COMPAS (https://compas.dev), an open-source Python-based framework for
    collaboration and research in architecture, engineering and digital fabrication.
  doc_url: https://gramaziokohler.github.io/compas_fab
  dev_url: https://github.com/compas-dev/compas_fab

extra:
  recipe-maintainers:
    - gonzalocasas
    - beverlylytle
    - romanarust
