{% set name = "compas_fab" %}
{% set version = "0.4.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "d99241436793674b653da0b2340bd3f86aef6726fc9bd25931cf2e720f6080ab" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  skip: True   # [linux and py27]
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - compas ==0.4.10
    - roslibpy >=0.4.0
    - pyserial

test:
  imports:
    - compas_fab
    - compas_fab.artists
    - compas_fab.robots

about:
  home: https://github.com/gramaziokohler/compas_fab
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Robotic fabrication package for the COMPAS Framework
  description: |
    Robotic fabrication package for the COMPAS Framework facilitating the
    planning and execution of robotic fabrication processes. It provides
    interfaces to existing software libraries and tools available in the
    field of robotics (e.g. OMPL, ROS) and makes them accessible from within
    the parametric design environment. The package builds upon
    COMPAS (https://compas-dev.github.io/), an open-source Python-based
    framework for collaboration and research in architecture, engineering
    and digital fabrication.
  doc_url: https://gramaziokohler.github.io/compas_fab
  dev_url: https://github.com/gramaziokohler/compas_fab

extra:
  recipe-maintainers:
    - gonzalocasas
